CREATE TABLE IF NOT EXISTS products(
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description VARCHAR NOT NULL,
	properties BYTEA NOT NULL,
	price INT NOT NULL CHECK(price > 0),
	amount INT NOT NULL CHECK (amount >= 0),
	version INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS images(
	id BIGSERIAL PRIMARY KEY,
	product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
	url VARCHAR(200) NOT NULL,
	version INTEGER NOT NULL DEFAULT 1
);
